bases:
  - ../../base
images:
  - name: ${image}
    newTag: "${imageTag}"
nameSuffix: -prod
commonLabels:
  app: ${app_name}-prod
patchesStrategicMerge:
  - patch.yaml
  # - configmap.yaml
  # - secret.yaml